bind '"\C-f": forward-word'
bind '"\C-b": backward-word'

BLUE=$(tput setaf 4)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
RED=$(tput setaf 1)
RESET=$(tput sgr0)

bg_jobs() {
  if [ -n "$(jobs -p)" ]; then echo " ${YELLOW}(\j)${RESET}"; fi
}

PROMPT_COMMAND='PS1="${BLUE}\w${RESET}$(__git_ps1 " ${GREEN}(%s)${RESET}") ${RED}\${?#0}${RESET}\$$(bg_jobs) "'

